import { ArrowRight, BrainCircuit, CalendarDays, FileSpreadsheet, LockKeyhole, MessageSquareText, ShieldCheck } from "lucide-react";

interface LandingPageProps { onLogin: () => void; }

const capabilities = [
    { icon: CalendarDays, title: "See the coverage picture", description: "Move between month, week, and day views to understand your shifts and the team roster at a glance." },
    { icon: FileSpreadsheet, title: "Bring your workbook", description: "Import a schedule from Excel and export a clean workbook when your team needs a familiar handoff." },
    { icon: MessageSquareText, title: "Make requests clearly", description: "Submit time-off and swap requests with the dates, coverage, and notes your scheduler needs to act." },
];

export function LandingPage({ onLogin }: LandingPageProps) {
    return (
        <div className="min-h-dvh bg-[#f5f8fc] text-[#102a43] selection:bg-[#0067a5]/15">
            <header className="border-b border-[#dce6f0] bg-white/90 backdrop-blur">
                <nav className="mx-auto flex w-full max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8" aria-label="Primary navigation">
                    <a href="#top" className="flex items-center gap-2.5 text-sm font-bold tracking-tight text-[#102a43]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#0067a5]/10 text-[#0067a5]"><BrainCircuit className="h-5 w-5" aria-hidden /></span>Neuro ICU Scheduling</a>
                    <div className="hidden items-center gap-7 text-sm font-medium text-[#526579] md:flex"><a href="#capabilities" className="transition-colors hover:text-[#0067a5]">Capabilities</a><a href="#workflow" className="transition-colors hover:text-[#0067a5]">Workflow</a><a href="#access" className="transition-colors hover:text-[#0067a5]">Access</a></div>
                    <button type="button" onClick={onLogin} className="min-h-11 rounded-lg bg-[#0067a5] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-[#005486] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#0067a5] focus-visible:ring-offset-2">Staff sign in</button>
                </nav>
            </header>
            <main id="top">
                <section className="mx-auto grid w-full max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:px-8">
                    <div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#b9d7e8] bg-white px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-[#0067a5]"><span className="h-2 w-2 rounded-full bg-[#2d9b78]" aria-hidden /> Cleveland Clinic · Neuro ICU</p><h1 className="max-w-2xl text-4xl font-semibold leading-[1.08] tracking-[-0.03em] text-[#102a43] sm:text-6xl">A clearer schedule. A better-covered team.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#526579]">One calm workspace for neuro ICU physicians and schedulers to publish coverage, review the team roster, and coordinate changes.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={onLogin} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-[#0067a5] px-5 py-3 text-sm font-semibold text-white shadow-md shadow-[#0067a5]/20 transition-colors hover:bg-[#005486] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#0067a5] focus-visible:ring-offset-2">Sign in to your schedule <ArrowRight className="h-4 w-4" aria-hidden /></button><a href="#capabilities" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-[#cbd9e5] bg-white px-5 py-3 text-sm font-semibold text-[#21415f] transition-colors hover:border-[#0067a5] hover:text-[#0067a5]">Explore the workspace</a></div><p className="mt-5 flex items-center gap-2 text-xs text-[#6b7d90]"><LockKeyhole className="h-3.5 w-3.5" aria-hidden /> Staff access is managed through the existing sign-in flow.</p></div>
                    <div id="workflow" className="rounded-2xl border border-[#cbd9e5] bg-white p-5 shadow-[0_18px_50px_rgba(16,42,67,0.08)] sm:p-7" aria-label="Schedule workspace preview"><div className="flex items-center justify-between border-b border-[#e5edf4] pb-4"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#7a8da0]">This week</p><p className="mt-1 text-lg font-semibold">Neuro ICU coverage</p></div><span className="rounded-full bg-[#e7f4ef] px-2.5 py-1 text-xs font-semibold text-[#237857]">Published</span></div><div className="mt-5 grid grid-cols-7 gap-1.5 text-center text-xs">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, index) => <div key={day} className="min-w-0"><p className="mb-2 font-semibold text-[#7a8da0]">{day}</p><div className={`min-h-24 rounded-lg border p-2 text-left ${index === 2 ? "border-[#0067a5] bg-[#edf7fc]" : "border-[#e5edf4] bg-[#fbfcfe]"}`}><span className="font-semibold text-[#21415f]">{index % 3 === 0 ? "Day" : index % 3 === 1 ? "Night" : "G20"}</span><span className="mt-2 block text-[10px] leading-4 text-[#6b7d90]">{index === 2 ? "You · 07:00" : "Coverage set"}</span></div></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-lg border border-[#dce6f0] bg-[#f7fafc] p-3 text-xs text-[#526579]"><ShieldCheck className="h-4 w-4 shrink-0 text-[#2d9b78]" aria-hidden /><span>Coverage changes stay visible to the scheduling team before they are applied.</span></div></div>
                </section>
                <section id="capabilities" className="border-y border-[#dce6f0] bg-white"><div className="mx-auto w-full max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#0067a5]">Built for the daily handoff</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-[#102a43]">The details physicians need, close at hand.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{capabilities.map(({ icon: Icon, title, description }) => <article key={title} className="rounded-xl border border-[#dce6f0] bg-[#fbfcfe] p-6"><Icon className="h-5 w-5 text-[#0067a5]" aria-hidden /><h3 className="mt-5 text-base font-semibold text-[#102a43]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#526579]">{description}</p></article>)}</div></div></section>
                <section id="access" className="mx-auto flex w-full max-w-7xl flex-col items-start gap-6 px-4 py-14 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><div><h2 className="text-2xl font-semibold tracking-tight text-[#102a43]">Ready to review your coverage?</h2><p className="mt-2 text-sm text-[#526579]">Sign in with your staff account to open the current schedule.</p></div><button type="button" onClick={onLogin} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#102a43] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#183d5c]">Open staff sign in <ArrowRight className="h-4 w-4" aria-hidden /></button></section>
            </main>
            <footer className="border-t border-[#dce6f0] bg-white"><div className="mx-auto flex w-full max-w-7xl flex-col gap-2 px-4 py-7 text-xs text-[#6b7d90] sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span className="font-semibold text-[#526579]">Neuro ICU Scheduling</span><span>Physician coverage coordination workspace</span></div></footer>
        </div>
    );
}
